export {default as Navbar} from './Navbar'
export {default as Slider} from './Slider'
export {default as Footer} from './Footer'
export {default as LandingPage} from './LandingPage'
export {default as LandingSection} from './LandingSection'